Add commit data and retry on init

diff --git a/.github/workflows/terraform-apply-reusable.yml b/.github/workflows/terraform-apply-reusable.yml
--- a/.github/workflows/terraform-apply-reusable.yml
+++ b/.github/workflows/terraform-apply-reusable.yml
@@ -58,7 +58,42 @@ jobs:
       - name: "terraform-init::${{ inputs.environment }}"
         id: init
         run: |
-          terraform init  -upgrade -backend-config=backend-configs/${{ inputs.environment }}-backend.tfvars && ./resources/tf_ws_select.sh ${{ inputs.environment }}
+          #!/bin/bash
+
+          command_to_execute="terraform init  -upgrade -backend-config=backend-configs/${{ inputs.environment }}-backend.tfvars"
+          timeout_seconds=300 # 5 minutes
+          max_retries=3
+
+          retry_count=0
+
+          while [ $retry_count -lt $max_retries ]; do
+            # Execute the command with a timeout
+            timeout $timeout_seconds $command_to_execute
+
+            # Check the exit status of the command
+            exit_status=$?
+            
+            if [ $exit_status -eq 0 ]; then
+              echo "Command executed successfully"
+              break
+            else
+              echo "Command failed with exit status $exit_status"
+              echo "Retrying..."
+              retry_count=$((retry_count + 1))
+            fi
+          done
+
+          if [ $retry_count -eq $max_retries ]; then
+            echo "Maximum retries reached. Exiting..."
+            exit 1
+          fi
+
+          ./resources/tf_ws_select.sh ${{ inputs.environment }}
+
+      - name: "terraform-validate::${{ inputs.environment }}"
+        id: validate
+        run: |
+          #!/bin/bash
           terraform validate
       - name: "terraform-apply::${{ inputs.environment }}"
         id: apply
